name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2
      - name: Run Feed Generator
        uses: codewith-usama/podcast-generator@main
      
